name: melloddy_combined
channels:
  - rdkit
  - defaults
  - conda-forge 
  - pytorch
  - pog87

dependencies:
  - mkl=2019.4
  - mkl_random=1.0.2
  - numpy=1.16.5
  - openssl=1.1.1d
  - jupyterlab
  - ptitprince=0.2.3
  - pandas=1.1.3
  - pip=19.2.2
  - python=3.6.9
  - rdkit=2019.03.4.0
  - scipy=1.3.1
  - sqlite=3.29.0
  - tqdm=4.32.1
  - nose2
  - pytest
  - pytorch
  - scikit-learn
  - pip
  - pip:
    - tensorboard==1.14.0
    - seaborn==0.10.0
